### ISSUE TITLE
Apply smart quotes on subtitle 

### ISSUE THREAD

**Issue by hatsumatsu** [benhuson/wp-subtitle#16]
It would be great if the `the_subtitle()` would automatically apply `wptexturize()` on its output to take advantage of smart quotes and all the other typographic miracles WP offers. 

I can make a PR if you like...

**Comment by benhuson** [comment]
Happy to merge a PR if you'd like to submit one :)

**Comment by benhuson** [comment]
Thanks for the PR.

It just prompted me to go and check how WordPress does this for `the_title()` in core.
Their approach seems to be to use the `the_title` filter to apply it rather than in the `the_title()` function.

I guess this makes sense as it allows people to disable these filters if they didn't want to texturize the title for any reason.

I'll adapt your patch slightly to use the filter method for the subtitle as I think this will give users greater flexibility if needed.

**Comment by benhuson** [comment]
Here's how it's applied using a filter: https://github.com/benhuson/wp-subtitle/commit/02375d063b4964f1b1bdca32816637e100b86cee

Thank you for your contribution :smile:
